"use client";
import { CssBaseline, ThemeProvider } from "@mui/material";
import Container from "@mui/material/Container";
import { Footer, Hero, NavBar } from "./components";
import "./globals.css";
import { lightTheme } from "./theme/themes";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={lightTheme}>
        <CssBaseline />
        <body>
          <NavBar />
          <Hero />
          <main>
            <Container>{children}</Container>
          </main>
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
