"use client";
import { CssBaseline, ThemeProvider } from "@mui/material";
import Container from "@mui/material/Container";
import { useEffect, useState } from "react";
import { Footer, Hero, NavBar } from "./components";
import "./globals.css";
import { lightTheme } from "./theme/themes";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [showLoginForm, setShowLoginForm] = useState(true);
  const [showSignupForm, setShowSignupForm] = useState(false);

  useEffect(() => {
    // Check if the user is logged in on page load
    const checkLoginStatus = async () => {
      try {
        const token = localStorage.getItem("token");
        console.log("token", token);

        const response = await fetch("http://localhost:3001/api/v1/profile", {
          method: "GET",
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        console.log("response", response);

        if (response.ok) setIsLoggedIn(true);
      } catch (error) {
        console.log(error);
      }
    };
    checkLoginStatus();
  }, []);

  const handleLogout = () => {
    localStorage.removeItem("token");
    setIsLoggedIn(false);
  };

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={lightTheme}>
        <CssBaseline />
        <body>
          <NavBar showLogOutButton={isLoggedIn} setIsLoggedIn={setIsLoggedIn} />
          <Hero
            isLoggedIn={isLoggedIn}
            showSignupForm={showSignupForm}
            setShowLoginForm={setShowLoginForm}
            setShowSignupForm={setShowSignupForm}
            setIsLoggedIn={setIsLoggedIn}
            showLoginForm={showLoginForm}
          />
          <main>
            <Container>{children}</Container>
          </main>
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
